### ISSUE TITLE
[enhancement] Provide error message for cl_main.lua:189

### ISSUE THREAD

**Issue by andrewpratt64** [Henotu/gmod-spotify-integration#2]
This is just a suggestion, but a custom message to replace the "attempt to index local 'tbl' (a nil value)" error might be a little more helpful for users who didn't read the "Common Bugs & fixes" portion of your addon page (such as myself; I have no clue how I missed it lol.) I'm assuming all this needs is an if statement to test if tbl is null right after it's initialized and calling error() if it is, but I haven't done too much with HTTP requests in Gmod before so I'm not positive.

**Comment by Henotu** [comment]
I'll look into it
